import { Job } from "./job-type";

export const jobData: Job[] = [
  {
    id: 101,
    image: "assets/images/job/ui-ux-job.png",
    title: "UI/UX IT Frontend Developer",
    location: "Salt Lake City, UT",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Full time",
    icon: "",
    featured: false,
    jobNature: "Designer",
  },
  {
    id: 102,
    image: "assets/images/job/react-job.png",
    title: "React/React Native Developer",
    location: "San Diego, CA",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Full time",
    icon: "",
    featured: true,
    jobNature: "React",
  },
  {
    id: 103,
    image: "assets/images/job/senior-job.png",
    title: "Senior UX designer",
    location: "Minneapolis, MN",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Part time",
    icon: "",
    featured: false,
    jobNature: "Senior designer",
  },
  {
    id: 104,
    image: "assets/images/job/design-job.png",
    title: "Front end web developer",
    location: "Cisco, Lelystad, Netherlands",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Full time",
    icon: "",
    featured: true,
    jobNature: "Designer",
  },
  {
    id: 105,
    image: "assets/images/job/ui-ux-job.png",
    title: "Graphic designer",
    location: "Infosys, Lelystad, Netherlands",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Internship",
    icon: "",
    featured: false,
    jobNature: "Designer",
  },
  {
    id: 106,
    image: "assets/images/job/ang-job.png",
    title: "Angular Developer",
    location: "(L6) Salt Lake City, UT",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Internship",
    icon: "",
    featured: false,
    jobNature: "Angular",
  },
  {
    id: 107,
    image: "assets/images/job/senior-job.png",
    title: "JAVA Developer",
    location: "(L6) Salt Lake City, UT",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Internship",
    icon: "",
    featured: false,
    jobNature: "java",
  },
  {
    id: 108,
    image: "assets/images/job/react-job.png",
    title: "React devoloper",
    location: "Infosys, Lelystad, Netherlands",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Part time",
    icon: "",
    featured: false,
    jobNature: "React",
  },
  {
    id: 109,
    image: "assets/images/job/ui-ux-job.png",
    title: "Business Managment",
    location: "Infosys, Lelystad, Netherlands",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Part time",
    icon: "",
    featured: false,
    jobNature: "Business",
  },
  {
    id: 110,
    image: "assets/images/job/senior-job.png",
    title: "Market Analysis",
    location: "Infosys, Lelystad, Netherlands",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Internship",
    icon: "",
    featured: false,
    jobNature: "Marketing",
  },
  {
    id: 111,
    image: "assets/images/job/ang-job.png",
    title: "Senior Angular Developer",
    location: "Infosys, Lelystad, Netherlands",
    description:
      "We are looking for an experienced and creative designer and/or frontend engineer with expertise in accessibility to join our team , 3+ years of experience working in as a Frontend Engineer or comparable role",
    qualification: [
      "Have shipped multiple iOS, Android, and/or web products.",
      "5+ years UI/UX experience.",
      "Ability to autonomously pursue elegant solutions to open-ended problems.",
      "Proven ability to create interactive prototypes.",
      "Ability to create and maintain flow charts, wire frames, prototypes, and mockups.",
      "Ability to effectively work on more than one project at a time.",
    ],
    jobType: "Internship",
    icon: "",
    featured: false,
    jobNature: "Designer",
  },
];
